[package]
name = "compute-with-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"
